services:
  - type: web
    name: atelier-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/atelier-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://amourexauceeyemandoko:Lilian190@cluster0.qoimeoz.mongodb.net/hackaton?retryWrites=true&w=majority&appName=Cluster0